In [1]:
from un_wpp import *
from un_wpp import _load_demographics

In [2]:
walden_ds = load_walden_ds()
tmp_dir = extract_data(walden_ds)
# df_population, df_fertility, df_demographics, df_depratio, df_deaths = load_data(
#     tmp_dir
# )

In [6]:
df_demographics[df_demographics.Variant.isna()]

,SortOrder,LocID,Notes,ISO3_code,ISO2_code,SDMX_code,LocTypeID,LocTypeName,ParentID,Location,...,Q0060Male,Q0060Female,Q1550,Q1550Male,Q1550Female,Q1560,Q1560Male,Q1560Female,NetMigrations,CNMR
44264,1,900,NaN,NaN,NaN,1,1,World,0,World,...,220.1434,151.9735,78.9306,95.6832,61.2972,152.9674,185.9613,118.4835,0.0,0.0
44265,1,900,NaN,NaN,NaN,1,1,World,0,World,...,197.0552,134.8658,70.3591,85.3943,54.5459,134.1482,163.9209,103.1299,0.0,0.0
44266,1,900,NaN,NaN,NaN,1,1,World,0,World,...,192.8104,131.4342,69.0734,83.8495,53.5236,131.3974,160.6534,100.9021,0.0,0.0
44267,1,900,NaN,NaN,NaN,1,1,World,0,World,...,190.9451,129.9093,68.6905,83.3434,53.2582,130.3275,159.2792,100.1221,0.0,0.0
44268,1,900,NaN,NaN,NaN,1,1,World,0,World,...,188.8532,128.1330,68.1153,82.6397,52.8075,129.2655,157.9456,99.3176,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
292859,290,876,2,WLF,WF,876,4,Country/Area,957,Wallis and Futuna Islands,...,23.1199,28.0450,7.4893,6.3613,8.6783,21.0053,20.2116,21.8411,0.0,0.0
292860,290,876,2,WLF,WF,876,4,Country/Area,957,Wallis and Futuna Islands,...,22.7966,27.4133,7.3438,6.2703,8.4752,20.6112,19.9248,21.3338,0.0,0.0
292861,290,876,2,WLF,WF,876,4,Country/Area,957,Wallis and Futuna Islands,...,22.4732,26.9919,7.2312,6.1793,8.3398,20.2993,19.6379,20.9955,0.0,0.0
292862,290,876,2,WLF,WF,876,4,Country/Area,957,Wallis and Futuna Islands,...,22.1497,26.6620,7.1334,6.0883,8.2346,20.0240,19.3509,20.7325,0.0,0.0
292863,290,876,2,WLF,WF,876,4,Country/Area,957,Wallis and Futuna Islands,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Process
df_population, df_fertility, df_demographics, df_depratio, df_deaths = process(
    df_population, df_fertility, df_demographics, df_depratio, df_deaths
)
# Initiate dataset
ds = init_dataset(dest_dir, walden_ds)
# Add tables to dataset
ds = add_tables_to_ds(
    ds, df_population, df_fertility, df_demographics, df_depratio, df_deaths
)

In [3]:
df = _load_demographics(tmp_dir)

In [4]:
df[df.Variant.isna()]

Empty DataFrame
Columns: [SortOrder, LocID, Notes, ISO3_code, ISO2_code, SDMX_code, LocTypeID, LocTypeName, ParentID, Location, VarID, Variant, Time, TPopulation1Jan, TPopulation1July, TPopulationMale1July, TPopulationFemale1July, PopDensity, PopSexRatio, MedianAgePop, NatChange, NatChangeRT, PopChange, PopGrowthRate, DoublingTime, Births, Births1519, CBR, TFR, NNR, MAC, SRB, Deaths, DeathsMale, DeathsFemale, CDR, LEx, LExMale, LExFemale, LE15, LE15Male, LE15Female, LE65, LE65Male, LE65Female, LE80, LE80Male, LE80Female, InfantDeaths, IMR, LBsurvivingAge1, Under5Deaths, Q5, Q0040, Q0040Male, Q0040Female, Q0060, Q0060Male, Q0060Female, Q1550, Q1550Male, Q1550Female, Q1560, Q1560Male, Q1560Female, NetMigrations, CNMR]
Index: []

[0 rows x 67 columns]

In [15]:
filenames = [
    f
    for f in filter(lambda x: "Demographic" in x, os.listdir(tmp_dir))
    if "notes" not in f
]

In [17]:
x = pd.concat(
    [pd.read_csv(os.path.join(tmp_dir, filename)) for filename in filenames],
    ignore_index=True,
)

/tmp/ipykernel_2552772/2527664120.py:3: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  pd.read_csv(os.path.join(tmp_dir, filename))
/tmp/ipykernel_2552772/2527664120.py:3: DtypeWarning: Columns (2,3,4) have mixed types. Specify dtype option on import or set low_memory=False.
  pd.read_csv(os.path.join(tmp_dir, filename))

In [20]:
x.Variant.unique()

array(['Medium', 'High', 'Low', 'Constant fertility',
       'Instant replacement', 'Zero migration', 'Constant mortality',
       'No change', 'Momentum', 'Instant replacement zero migration'],
      dtype=object)